### ISSUE TITLE
Not able to run it

### ISSUE THREAD

**Issue by Durrah** [canunot/CSCI212#1]
Hello, 
I've seen your code and tried to run it but I'm not able to do so. I'm using VMWare player to run it. Can u kindly let me know a step by step process to run it successfully?
Thank you

**Comment by canunot** [comment]
If youre talking about assignment 3. You need to make sure program is running as background process.

**Comment by Durrah** [comment]
I'm trying to run assignment 2.

**Comment by Durrah** [comment]
I've never tried running this kind of program before so I'm not sure of the commands to use while running. Can i Kindly know should I make it run as the background process...like what commands do i type to get the 1st screenshot as my output (where it says server Id has started with PID 3224)? Also which file should I run?
